# Generated by Django 3.0.7 on 2020-06-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alimentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theType', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(blank=True, default='Disponible', max_length=500)),
                ('disponibles', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='suplementos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theType', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(blank=True, default='Disponible', max_length=500)),
                ('disponibles', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
